# Generated by Django 5.2.13 on 2026-05-01 01:16

from django.db import migrations, models

class Migration(migrations.Migration):
# News 모델을 생성하는 초기 migration
    initial = True
# 선행될 migration 목록
    dependencies = [
    ]
# 데이터베이스에 적용될 작업 목록
    operations = [
        migrations.CreateModel(
            # 생성할 모델 이름
            name='News',
            # 모델의 필드 정의
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='뉴스 제목')),
                ('link', models.URLField(max_length=500, unique=True, verbose_name='원문 링크')),
                ('description', models.TextField(verbose_name='뉴스 요약')),
                ('pub_date', models.DateTimeField(verbose_name='발행일')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='썸네일 이미지 링크')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스 목록',
                'ordering': ['-pub_date'],
            },
        ),
    ]
