# Generated by Django 5.2.13 on 2026-05-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='댓글 수'),
        ),
    ]
