# Generated by Django 5.2.13 on 2026-05-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment_count',
        ),
    ]
