# Generated by Django 5.2.13 on 2026-05-03 01:15
# 뉴스 모델에 반응 수(reaction_count) 필드 추
from django.db import migrations, models


class Migration(migrations.Migration):
# 이전 마이그레이션 파일 의존성 설정
    dependencies = [
        ('news', '0003_remove_news_comment_count'),
    ]
# 데이터베이스 변경 작업 정의
    operations = [
        migrations.AddField(
            model_name='news',     # news 모델 수정
            name='reaction_count',    # 반응 수 필드 이름
            field=models.IntegerField(default=0, verbose_name='반응 수'),    # Django admin 등에 표시될 이름
        ),
    ]
