# Generated by Django 5.2.13 on 2026-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reaction_count',
            field=models.IntegerField(default=0, verbose_name='반응 수'),
        ),
    ]
